#!/bin/bash

echodo() {
  echo "${@}"
  ${@}
}

# prepare transifex 
#if [ ! -s  .tx/config ]; then
   mkdir -p .tx
   cat <<EOF > .tx/config
[main]
host = https://www.transifex.com

[antix-development.mx-boot-options]
file_filter = ./mx-boot-options_<lang>.ts
source_file = mx-boot-options_en.ts
source_lang = en
type = ts
EOF
#fi    

# get all translations
if command -v tx >/dev/null; then
   echodo tx pull -r antix-development.mx-boot-options  --all
fi

